[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/debug/enquiries"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"